/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import gestores.GestorProducto;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ema
 */
public class MenuDeGestionDeProductos extends javax.swing.JFrame {

    /**
     * Creates new form MenuDeGestionDeProductos
     */
    public MenuDeGestionDeProductos() {
        initComponents();
        agregarProductosATabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigoDeBarraProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextDescripcion = new javax.swing.JTextField();
        jButtonBuscarProducto = new javax.swing.JButton();
        jLabelMensajeDeAdvertencia = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonIngresarNuevoProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de Gestion de Productos");
        setExtendedState(MenuDeGestionDeProductos.MAXIMIZED_BOTH);

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo del Producto", "Descripcion del Producto", "Stock", "Precio de Costo", "Alicuota", "Precio Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Short.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.setLayout(new java.awt.GridLayout(3, 4, 30, 15));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Codigo de barra del Producto:");
        jPanel1.add(jLabel2);

        jTextFieldCodigoDeBarraProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCodigoDeBarraProductoMouseClicked(evt);
            }
        });
        jTextFieldCodigoDeBarraProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoDeBarraProductoActionPerformed(evt);
            }
        });
        jTextFieldCodigoDeBarraProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCodigoDeBarraProductoFocusGained(evt);
            }
        });
        jTextFieldCodigoDeBarraProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoDeBarraProductoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoDeBarraProducto);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Descripción del Producto:");
        jPanel1.add(jLabel1);

        jTextDescripcion.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextDescripcionCaretUpdate(evt);
            }
        });
        jTextDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescripcionActionPerformed(evt);
            }
        });
        jTextDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextDescripcionFocusGained(evt);
            }
        });
        jPanel1.add(jTextDescripcion);

        jButtonBuscarProducto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBuscarProducto.setText("Buscar Producto");
        jButtonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarProducto);

        jLabelMensajeDeAdvertencia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelMensajeDeAdvertencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensajeDeAdvertencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelMensajeDeAdvertencia);

        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jButtonIngresarNuevoProducto.setBackground(new java.awt.Color(204, 204, 204));
        jButtonIngresarNuevoProducto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonIngresarNuevoProducto.setText("NUEVO");
        jButtonIngresarNuevoProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 204), null, null, new java.awt.Color(204, 0, 204)));
        jButtonIngresarNuevoProducto.setFocusable(false);
        jButtonIngresarNuevoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonIngresarNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarNuevoProductoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonIngresarNuevoProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoDeBarraProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoDeBarraProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoDeBarraProductoActionPerformed

    private void jButtonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProductoActionPerformed
        // TODO add your handling code here:
        validar();
        Integer numero = 0;
        String descripcion = jTextDescripcion.getText();
        try{
            numero = parseInt(jTextFieldCodigoDeBarraProducto.getText());
        }catch(NumberFormatException exc) {
        }
        if (numero != 0) {

            Object[] productoBuscado = {GestorProducto.ConsultaProducto(numero).getCodigoDeProducto(),
                GestorProducto.ConsultaProducto(numero).getNombreProducto(),
                GestorProducto.ConsultaProducto(numero).getStockProducto(),
                GestorProducto.ConsultaProducto(numero).getPrecioUnitario()};

            DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();

            borrarRenglones();
            tabla.insertRow(0, productoBuscado);
        }
    }//GEN-LAST:event_jButtonBuscarProductoActionPerformed

    private void jTextFieldCodigoDeBarraProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCodigoDeBarraProductoMouseClicked
        // TODO add your handling code here:
        jTextFieldCodigoDeBarraProducto.setBackground(Color.white);
        jLabelMensajeDeAdvertencia.setText(" ");
    }//GEN-LAST:event_jTextFieldCodigoDeBarraProductoMouseClicked

    private void jButtonIngresarNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarNuevoProductoActionPerformed
        AltaProducto ventanaAltaProducto = new AltaProducto();
        ventanaAltaProducto.setVisible(true);
    }//GEN-LAST:event_jButtonIngresarNuevoProductoActionPerformed

    private void jTextDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescripcionActionPerformed

    private void jTextDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDescripcionFocusGained
        jTextFieldCodigoDeBarraProducto.setText(null); // Borra el contenido del campo de busqueda por codigo
    }//GEN-LAST:event_jTextDescripcionFocusGained

    private void jTextDescripcionCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextDescripcionCaretUpdate
        borrarRenglones();
        buscarMientrasEscribe();
    }//GEN-LAST:event_jTextDescripcionCaretUpdate

    private void jTextFieldCodigoDeBarraProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodigoDeBarraProductoFocusGained
        jTextDescripcion.setText(null);
    }//GEN-LAST:event_jTextFieldCodigoDeBarraProductoFocusGained

    private void jTextFieldCodigoDeBarraProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoDeBarraProductoKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodigoDeBarraProductoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeGestionDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeGestionDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeGestionDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeGestionDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDeGestionDeProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarProducto;
    private javax.swing.JButton jButtonIngresarNuevoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMensajeDeAdvertencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextFieldCodigoDeBarraProducto;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    private String paraBuscar;
    
    private void validar() {
        if (jTextFieldCodigoDeBarraProducto.getText().isEmpty() && jTextDescripcion.getText().isEmpty()) {
            borrarRenglones();
            agregarProductosATabla();
        }
    }

    private void agregarProductosATabla() {
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        if (GestorProducto.listarProductosDB().size() != 0) {
            for (int i = 0; i < GestorProducto.listarProductosDB().size(); i++) {
                Object[] fila = {GestorProducto.listarProductosDB().get(i).getCodigoDeProducto(),
                    GestorProducto.listarProductosDB().get(i).getNombreProducto(),
                    GestorProducto.listarProductosDB().get(i).getStockProducto(),
                    GestorProducto.listarProductosDB().get(i).getPrecioUnitario()};
                tabla.addRow(fila);
            }
        }
    }
    private void borrarRenglones(){
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tabla.removeRow(i); //se van borrando para que solo muestre el producto que se buscó
        }
    }
        private void buscarMientrasEscribe() {
        paraBuscar = jTextDescripcion.getText();
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        if (GestorProducto.ConsultaPorDescripcion(paraBuscar).size() != 0) {
            borrarRenglones();
            for (int i = 0; i < GestorProducto.ConsultaPorDescripcion(paraBuscar).size(); i++) {
                Object[] fila = {GestorProducto.ConsultaPorDescripcion(paraBuscar).get(i).getCodigoDeProducto(),
                GestorProducto.ConsultaPorDescripcion(paraBuscar).get(i).getNombreProducto(),
                GestorProducto.ConsultaPorDescripcion(paraBuscar).get(i).getStockProducto(),
                GestorProducto.ConsultaPorDescripcion(paraBuscar).get(i).getPrecioUnitario()};
                tabla.addRow(fila);
            }
        }
    }
}
